version: "3.8"

services:

  online_shop:
    build:
      context: .
    container_name: online-shop
    ports:
      - "80:80"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 60s
      timeout: 10s
      retries: 5
    networks:
      - online-shop

networks:
  online-shop:
    driver: bridge
